version: '3.7'
services:
  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: ./Dockerfile.mysql
    volumes:
      - mysqldb:/var/lib/mysql
    environment:
      - MYSQL_USER=external_user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=my_database
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks: 
      - my_network
  http-server:
    container_name: http-server
    build:
      context: .
      dockerfile: ./Dockerfile.http-server
    ports:
      - "8888:8888"
    networks: 
      - my_network
volumes:
  mysqldb:
networks:
  my_network: