services:
  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: ./Docker/Dockerfile.mysql
    volumes:
      - mysqldb:/var/lib/mysql
      - ./certs:/etc/mysql/certs 
    environment:
      - MYSQL_USER=external_user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=my_database
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks: 
      - my_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 5s
  http-server:
    container_name: http-server
    build:
      context: .
      dockerfile: ./Docker/Dockerfile.http-server
    volumes:
      - ./certs:/etc/mysql/certs
    environment:
      - MYSQL_USER=external_user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=my_database
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8443:8443"
    networks: 
      - my_network
volumes:
  mysqldb:
networks:
  my_network:
    driver: bridge
