FROM mysql:latest

RUN test -n $MYSQL_USER
RUN test -n $MYSQL_PASSWORD
RUN test -n $MYSQL_DATABASE

WORKDIR /app

ADD . /app

RUN chmod +x /app/Docker/generate-sql-ssl.sh

CMD /app/Docker/generate-sql-ssl.sh